export const GET_CLUB_DATA = "GET_CLUB_DATA";
export const GET_USER_DATA = "GET_USER_DATA";
export const STORE_GAME_DATA = "STORE_GAME_DATA";
export const LIST_OF_EMPLOYEE_TYPES = "LIST_OF_EMPLOYEE_TYPES";
export const SET_EMPLOYEE_TYPE = "SET_EMPLOYEE_TYPE";
